name: chatify
services:
  app-server:
    build:
      context: ./server
    container_name: chatify-server
    ports:
      - 5001:5001
    restart: always
    env_file: ./server/.env
    environment:
      NODE_ENV: production
      PORT: 5001
      ALLOWED_ORIGINS: http://localhost:3000
    healthcheck:
      test: curl --fail http://localhost:5001/api/ping
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s

  app-client:
    build:
      context: ./client
      args:
        NODE_ENV: production
        PORT: 3000
        HOST: localhost
        NEXT_PUBLIC_BACKEND_URL: http://localhost:5001
        NEXT_PUBLIC_FIREBASE_CONFIG: ${NEXT_PUBLIC_FIREBASE_CONFIG}
    container_name: chatify-client
    ports:
      - 3000:3000
    restart: always
    # env_file: ./client/.env # doesn't work with next, it only
    # environment: # doesn't work with next
    #   NODE_ENV: production
    #   PORT: 3000
    #   HOST: localhost
    #   NEXT_PUBLIC_BACKEND_URL: http://localhost:5001
    # depends_on:
    #   app-server:
    #     condition: service_healthy
