import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {ThemeProvider} from "@/app/_providers/theme/theme-provider";
import {IntlProvider} from "@/app/_providers/intl/intl-provider";
import {Navbar} from "@/components/navbar";
import {Footer} from "@/components/footer";
import {SWRProvider} from "@/app/_providers/swr";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {

  return (
    <html lang="en">
    <body className="antialiased">
    <SWRProvider>
      <IntlProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <main className="min-w-screen min-h-screen pt-[4.5rem] relative">
            <Navbar/>
            {children}
            <Footer/>
          </main>
        </ThemeProvider>
      </IntlProvider>
    </SWRProvider>
    </body>
    </html>
  );
}
