import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {ThemeProvider} from "@/app/_providers/theme/theme-provider";
import {IntlProvider} from "@/app/_providers/intl/intl-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {

  return (
    <html lang="en">
    <body className="antialiased">
    <IntlProvider>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        {children}
      </ThemeProvider>
    </IntlProvider>
    </body>
    </html>
  );
}
